services:
  - type: web
    name: coronel-sur
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0
